### ISSUE TITLE
Support pagination as a first class citizen in lib-api

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster-lib-api#63]
We've been working towards making pagination supported as a first class citizen.  We should formalize a couple things around it.

Proposal is:

1. block use of 'limit' or 'continuationToken' from the query string options allowed
2. add a `pagination: true` value to the api.declare
3. When pagination is set to true, the api will add a `pagination: true` to the api reference, which will then allow clients to do automatic pagination.  In the interim, we should automatically add the limit and continuationToken to the query string options allowed

**Comment by djmitche** [comment]
I might have missed discussion of this when vidyo cut out, but some of the tools take these parameters in a POST, and some take them as query args.  I'm not sure if there's good reason for that, but it will need to be considered whether to change to query-args everywhere, or support both modes.

**Comment by djmitche** [comment]
Let's cover this in https://bugzilla.mozilla.org/show_bug.cgi?id=1405072
