### ISSUE TITLE
having 'deferAuth: False' should cause req.satisfies to throw an error

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster-lib-api#69]
Right now, if you have deferAuth: false or not given as an option, and you call req.satisfies, the result is that your response handler just silently runs twice.  This is not ideal and it's a really weird bug.

What we should do is if a method has deferAuth with a falsy value, we should check the auth but pass into the request handler a method `req.satisfies = () => { throw new Error("Cannot run req.satisifies on a non-defered auth request"}` instead of allowing the auth handler to run a second time.  Because req.satisfies is implemented as a middleware, the next() method gets run twice, which is the duplication of the response body handler

@jonasfj @imbstack

**Comment by jonasfj** [comment]
This is all going away in the future, see:
https://github.com/taskcluster/taskcluster-lib-api/pull/68
https://github.com/taskcluster/taskcluster-rfcs/issues/23

**Comment by djmitche** [comment]
@jhford any reason to keep this open, now that deferAuth and req.satisfies are gone?
