### ISSUE TITLE
Scope-expression template validation not strict enough

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-lib-api#75]
The following in `api.declare` does not cause an load-time error:
```js
    scopes: {AllOf: {for: 'scope', in: 'requiredScopes', each: '<scope>'}},
```

**Comment by djmitche** [comment]
@jonasfj is this still the case?  Perhaps a bugzilla bug is in order?

**Comment by jonasfj** [comment]
I suspect this got fixed in the refactor... otherwise we can reopen..
